plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
title: 'Lessy.app legal documents'
include:
  - index.md
  - en/user_agreement.md
  - en/license_agreement.md
  - en/privacy_policy.md
