title: 'Lessy.app'
author: 'Lessy'
repository: 'lessy-legal/legal'
url: 'https://legal.lessy.tech'
language: 'en'
sass:
  sass_dir: assets/css/
  style: compressed
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true